name: Fullstack_Gestion_Formacion

services:
# Development Services
  frontend-dev:
    profiles: ["dev"]
    container_name: frontend
    image: frontend:latest
    build:
      context: ./GestionFormacionFrontEnd
      dockerfile: front.Dockerfile
      target: dev
    ports:
      - "8080:8080"
    networks:
      - dev-net
    volumes:
      - ./GestionFormacionFrontEnd:/app
    depends_on:
      backend-dev:
        condition: service_started
    stdin_open: true
    tty: true
       
  backend-dev:
    profiles: ["dev"]
    container_name: backend
    image: backend:latest
    build: 
      context: ./GestionFormacion
      dockerfile: back.Dockerfile
      target: dev
    networks:
      - dev-net
    ports:
      - "8000:8000"
    volumes:
      - ./GestionFormacion:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_NAME=gestion_formacion
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD={DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

# Production Ready Services
  nginx-webserver:
    profiles: ["prod"]
    container_name: nginx_webserver
    image: frontend:latest
    build:
      context: ./GestionFormacionFrontEnd
      dockerfile: front.Dockerfile
      target: prod
    ports:
      - "80:80"
    networks:
      - prod-net
    depends_on:
      fastapi-services:
          condition: service_started
    stdin_open: true
    tty: true
       
  fastapi-services:
    profiles: ["prod"]
    container_name: fastapi_backend_server
    image: backend:latest
    build: 
      context: ./GestionFormacion
      dockerfile: back.Dockerfile
      target: prod
    networks:
      -  prod-net
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true


# Default Services
  db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  prod-net:
  dev-net:

volumes:
  mysql_data: